In [91]:
# import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [92]:
df = pd.read_csv("data/cleaned_diabetic_data.csv")
df.shape

(63595, 40)

In [93]:
df.head()

,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,...,miglitol,troglitazone,tolazamide,insulin,glyburide-metformin,glipizide-metformin,metformin-pioglitazone,change,diabetesMed,readmitted
0,Caucasian,Female,[40-50),1,4,7,14,69,0,16,...,No,No,No,Down,No,No,No,Ch,Yes,0
1,Other,Female,[40-50),1,1,7,14,73,6,26,...,No,No,No,Up,No,No,No,Ch,Yes,0
2,Hispanic,Female,[50-60),1,6,7,14,69,0,25,...,No,No,No,Steady,No,No,No,No,Yes,0
3,AfricanAmerican,Male,[40-50),1,6,7,14,65,2,34,...,No,No,No,Up,No,No,No,Ch,Yes,0
4,Caucasian,Male,[50-60),3,1,1,14,63,4,30,...,No,No,No,Down,No,No,No,Ch,Yes,0

In [94]:
df.isnull().sum()

race                        0
gender                      0
age                         0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            0
A1Cresult                   0
metformin                   0
repaglinide                 0
nateglinide                 0
chlorpropamide              0
glimepiride                 0
acetohexamide               0
glipizide                   0
glyburide                   0
tolbutamide                 0
pioglitazone                0
rosiglitazone               0
acarbose                    0
miglitol                    0
troglitazone                0
tolazamide                  0
insulin                     0
glyburide-metformin         0
glipizide-metformin         0
metformin-pioglitazone      0
change                      0
diabetesMed                 0
readmitted                  0
dtype: int64

In [95]:
df.duplicated().sum()

np.int64(0)

In [96]:
df["readmitted"].value_counts()

readmitted
0    59058
1     4537
Name: count, dtype: int64

### Feature Engineering

In [97]:
df.head()

,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,...,miglitol,troglitazone,tolazamide,insulin,glyburide-metformin,glipizide-metformin,metformin-pioglitazone,change,diabetesMed,readmitted
0,Caucasian,Female,[40-50),1,4,7,14,69,0,16,...,No,No,No,Down,No,No,No,Ch,Yes,0
1,Other,Female,[40-50),1,1,7,14,73,6,26,...,No,No,No,Up,No,No,No,Ch,Yes,0
2,Hispanic,Female,[50-60),1,6,7,14,69,0,25,...,No,No,No,Steady,No,No,No,No,Yes,0
3,AfricanAmerican,Male,[40-50),1,6,7,14,65,2,34,...,No,No,No,Up,No,No,No,Ch,Yes,0
4,Caucasian,Male,[50-60),3,1,1,14,63,4,30,...,No,No,No,Down,No,No,No,Ch,Yes,0

In [98]:
df["diag_2"].unique()

array(['305', '599', '276', '250.82', '682', '507', '785', '300', 'V54',
       '707', 'V62', '780', '518', 'V45', '799', '440', '486', '428',
       '788', '436', '492', '789', '997', '427', '250.22', '263', '574',
       '250.6', '425', '517', '403', '153', '491', '198', '496', '998',
       '8', '416', '250', '285', '424', '493', '585', '584', '569', '426',
       '250.41', '250.7', '511', '414', '821', '995', '411', '415', '790',
       '721', '250.02', '38', '730', '41', '401', '197', 'V49', '648',
       '421', '438', '553', '850', '250.93', '453', '396', '852', '40',
       '576', '340', '596', '571', '196', '250.52', '410', '331', '431',
       '433', '531', '189', '711', '203', '560', '434', '253', '294',
       '157', '200', '250.01', '482', '781', '820', '578', '272', '185',
       '577', '728', '277', '286', '332', '797', '557', '787', '342',
       '296', '404', '304', '284', '311', '485', '515', '162', '535',
       '250.81', '250.03', '250.4', '348', '437', '996', '312', '861',
       '512', 'V57', '566', 'V12', '319', '805', '413', '287', '292',
       '250.83', '444', '155', '295', '733', '824', '581', '686', '715',
       '112', '706', 'V42', '723', '324', '681', '293', '786', '250.12',
       '567', '550', '595', '719', '344', '729', 'V70', '398', '290',
       '346', '494', '443', '191', '808', '244', 'E878', '592', 'V43',
       '205', '851', '54', '250.92', '441', '601', '280', 'V15', 'V63',
       '250.42', '117', '156', '705', '722', '303', '70', '782', '724',
       '552', '590', '42', '262', '430', 'E950', '288', '745', '684',
       '250.8', '572', '905', '710', '536', '402', '397', '481', '530',
       '309', '807', '456', '394', '562', '242', '731', '301', '591',
       '716', '510', '152', '250.5', '154', '575', '907', '867', 'V85',
       'V66', '307', '451', '298', '278', '865', '273', 'E928', '250.13',
       '873', '336', '250.43', 'E885', '357', '204', '429', 'V11', '519',
       '532', '188', '53', '325', '202', '358', '881', 'V58', '192',
       '317', '282', '174', 'E888', 'E884', '349', '860', '487', '435',
       '573', '135', '362', '465', '579', '516', '446', '564', '250.2',
       '714', 'V46', '508', '800', '180', '823', '784', '308', '420',
       '696', '151', '291', '172', '464', '795', '709', '345', '741',
       '466', '322', '540', '137', '737', '812', '751', '537', '94',
       '600', '299', '337', '447', '570', '320', '864', '473', '150',
       '802', '920', '999', 'V10', '261', 'V64', '814', '368', '250.21',
       '459', '619', '611', '608', '565', '255', '555', '742', '922',
       '250.11', '568', '223', '826', '136', '138', '813', '250.51',
       '423', '208', '252', '816', '478', '211', 'V08', '432', '306',
       '513', '383', '260', '232', 'E931', '323', '275', 'E942', 'V44',
       '335', '35', '756', '558', '534', '333', '853', '694', '250.53',
       '607', '75', '987', '825', 'E934', '748', '11', '238', '289',
       '556', '250.31', '183', '250.32', '484', 'E880', 'E947', '726',
       '412', '746', '372', '343', '457', '455', 'E936', '583', '250.1',
       '442', '831', '680', '593', '233', '642', 'V09', '490', '454', '5',
       '377', '353', 'V02', '480', '924', '283', '458', '201', '199',
       '791', '218', '713', '810', '944', '9', '359', '725', '845', '528',
       '274', '386', '783', '360', 'E879', 'E932', '462', '894', '923',
       '514', 'E818', '327', '250.33', 'E849', '958', '314', '356', '614',
       '27', 'E933', '846', '753', '79', '269', '967', '388', '228',
       '365', '692', '212', '110', '501', '182', '251', '297', '934',
       '615', '815', '302', '461', 'E917', '78', 'E918', '163', 'E905',
       'E937', '644', 'E944', '46', '171', '380', '868', '698', '738',
       '661', '952', '794', '910', '279', '625', '652', '604', '495',
       'E939', '870', '840', '862', '685', '882', '792', '193', '452',
       '892', '241', '712', 'V69', '310', '524', '717', '145', '405',
       '281', '378', '750', '483', 'E935', '891', '588', '354', '141',
       'V14', '220', 'V65', '933', 'E870', '250.23', '533', '603', '527',
       '620', '580', '460', 'E881', 'E980', 'E813', '921', '646', 'E930',
       '621', '913', '822', '338', '500', '912', '695', '542', 'E887',
       '594', '847', '369', '837', '355', 'E916', 'E927', '616', '833',
       '989', '422', '693', '836', '522', '214', '195', '959', '893',
       '727', '215', 'V17', '796', '703', 'E882', '266', '586', '627',
       'V23', '258', 'V25', '918', '250.91', '659', '521', '942', '955',
       '758', '832', '225', '806', '718', '991', '463', 'V16', '736',
       '239', '617', '389', '844', '99', '656', '701', '543', 'V13',
       '318', '974', '945', '373', '702', '906', '963', '626', 'E919',
       '475', '670', '793', 'E900', '250.3', '240', '927', '647', '883',
       '250.9', 'E883', 'V18', '66', '179', 'E829', '866', '34', '863',
       'E812', 'E858', '618', 'E924', '374', '602', '523', '919', '801',
       '759', '843', '664', '352', 'E850', '869', '842', 'E929', '665',
       'E819', '747', '474', '947', '658', '969', '610', '641', '598',
       '131', 'E816', '948', '645', '382', 'E906', 'E821', '472', '872',
       '381', '245', '871', '7', '395', '477', '623', '968', '663', '246',
       '691', 'E817', '909', '654', 'V53', '994', 'V72', '351', 'E915',
       '227', '164', '123', '755', '268', '140', '316', '649', '622',
       '634', '376', '965', 'E968', 'V50', '350', '88', '470', '529',
       '448', 'E814', '880', 'E938', 'V86', 'E826', '347', '972', '911',
       'E853', '270', 'E868', '379', '734', '173', '992', '811', '226',
       'V60', '520', 'E890', '217', '271'], dtype=object)

In [99]:
def map_diagnosis_codes(code):
    code = str(code)
    if code.startswith("V") or code.startswith("E"):
        return "other"

    try:
        code_num = float(code)
    except ValueError:
        return "other"
    if 250 <= code_num < 251:
        return "Diabetes"
    elif (390 <=  code_num <= 459) or code_num == 785:
        return "Circulatory"
    elif (460 <= code_num <= 519) or code_num == 786:
        return "Respiratory"
    elif (520 <= code_num <= 579) or code_num == 787:
        return "Digestive"
    elif (580 <= code_num <= 629) or code_num == 788:
        return "Genitourinary"
    elif 800 <= code_num <= 999:
        return "Injury"
    elif 710 <= code_num <= 739:
        return "Musculoskeletal"
    elif 140 <= code_num <= 239:
        return "Neoplasms"
    else:
        return "other"
for col in ["diag_1","diag_2","diag_3"]:
    df[col] = df[col].apply(map_diagnosis_codes)

print(df["diag_1"].value_counts())

diag_1
Circulatory        19118
other              11426
Respiratory         8592
Digestive           6093
Diabetes            4793
Injury              4402
Musculoskeletal     3551
Genitourinary       3269
Neoplasms           2351
Name: count, dtype: int64

In [100]:
df["diag_1"].unique()

array(['other', 'Genitourinary', 'Circulatory', 'Diabetes', 'Respiratory',
       'Injury', 'Digestive', 'Neoplasms', 'Musculoskeletal'],
      dtype=object)

In [101]:
df["diag_2"].unique()

array(['other', 'Genitourinary', 'Diabetes', 'Respiratory', 'Circulatory',
       'Injury', 'Digestive', 'Neoplasms', 'Musculoskeletal'],
      dtype=object)

In [102]:
df["diag_3"].unique()

array(['Diabetes', 'Respiratory', 'Circulatory', 'Injury', 'Digestive',
       'other', 'Neoplasms', 'Genitourinary', 'Musculoskeletal'],
      dtype=object)

In [103]:
# Age
df["age"].unique()

array(['[40-50)', '[50-60)', '[60-70)', '[80-90)', '[30-40)', '[90-100)',
       '[70-80)', '[20-30)', '[10-20)', '[0-10)'], dtype=object)

In [104]:
age_order = [f"[{i}-{i+10})" for i in range(0, 100, 10)]
age_map = {age: i for i, age in enumerate(age_order)}
df["age"] = df["age"].map(age_map)

df["age"].unique()

array([4, 5, 6, 8, 3, 9, 7, 2, 1, 0])

In [105]:
df["age"].value_counts()

age
7    16148
6    14312
5    11269
8    10364
4     6089
3     2380
9     1684
2      961
1      329
0       59
Name: count, dtype: int64

In [106]:
df["total_prior_visits"] = df["number_outpatient"] + df["number_emergency"] + df["number_inpatient"]
print(df[["number_outpatient" , "number_emergency","number_inpatient","total_prior_visits"]].head())

   number_outpatient  number_emergency  number_inpatient  total_prior_visits
0                  0                 0                 0                   0
1                  0                 1                 0                   1
2                  0                 0                 1                   1
3                  1                 0                 1                   2
4                  0                 0                 0                   0

In [107]:
df.shape

(63595, 41)

### One_Hot_Encoding

In [108]:
df.head()

,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,...,troglitazone,tolazamide,insulin,glyburide-metformin,glipizide-metformin,metformin-pioglitazone,change,diabetesMed,readmitted,total_prior_visits
0,Caucasian,Female,4,1,4,7,14,69,0,16,...,No,No,Down,No,No,No,Ch,Yes,0,0
1,Other,Female,4,1,1,7,14,73,6,26,...,No,No,Up,No,No,No,Ch,Yes,0,1
2,Hispanic,Female,5,1,6,7,14,69,0,25,...,No,No,Steady,No,No,No,No,Yes,0,1
3,AfricanAmerican,Male,4,1,6,7,14,65,2,34,...,No,No,Up,No,No,No,Ch,Yes,0,2
4,Caucasian,Male,5,3,1,1,14,63,4,30,...,No,No,Down,No,No,No,Ch,Yes,0,0

In [109]:
df.dtypes.value_counts()

object    27
int64     14
Name: count, dtype: int64